basePath: /api/
definitions:
  handler.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  handler.RegisterSuccess:
    properties:
      email:
        type: string
      fullname:
        type: string
      id:
        type: integer
    type: object
  handler.SignInSuccess:
    properties:
      token:
        type: string
    type: object
  handler.SuccessResponse:
    properties:
      data: {}
      status:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: Your API description.
  title: Twittir Go API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Logs in a user and returns a token
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.SignInSuccess'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Login user
      tags:
      - Auth
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Fullname
        in: body
        name: fullname
        required: true
        schema:
          type: string
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Password verification
        in: body
        name: password_verify
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.RegisterSuccess'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Register user
      tags:
      - Auth
swagger: "2.0"
